### ISSUE TITLE
Support for CJSX?

### ISSUE THREAD

**Issue by willembult** [janraasch/gulp-coffeelint#24]
Any chance we could add this? I've created a fork and it's as simple as requiring [`coffeelint-cjsx`](https://github.com/emorikawa/coffeelint-cjsx) instead of `coffeelint`. Maybe we could pass in an option that changes the require?

**Comment by janraasch** [comment]
That would not be compliant with `gulp`'s plugin rules.

The best solution (according to a similar discussion on `gulp-jshint`, see https://github.com/spenceralger/gulp-jshint/issues/55) would probably be to use the existing `gulp-coffee-react-transform` plugin and simply do

```coffee
.pipe coffee_react_transform()
.pipe coffeelint()
```
