### ISSUE TITLE
add custom reporters or add a means of passing options to `coffelint`

### ISSUE THREAD

**Issue by amagura** [janraasch/gulp-coffeelint#26]
I prefer how vanilla `coffeelint` styles its output to the _stylish_ output used by `gulp-coffeelint`.  Could you perhaps make it possible to use custom reporters or make it so that the default `coffeelint` reporter could be used?

**Comment by janraasch** [comment]
After a `file` was piped through `coffeelint`, e.g.

```js
gulp.src('./src/*.coffee')
        .pipe(coffeelint())
```

the results from `coffeelint` are to be found under `file.coffeelint` (see https://github.com/janraasch/gulp-coffeelint#results), so you can use whatever you like to print those results to the console.

See https://github.com/janraasch/gulp-coffeelint/blob/master/lib/reporter.coffee for example code.
