### ISSUE TITLE
Coffeelint version out of date

### ISSUE THREAD

**Issue by pghalliday** [janraasch/gulp-coffeelint#27]
Would like to use the support for JSX and/or transforms in current version (1.8). Maybe you could use `peerdependencies` to unlink the version some

**Comment by janraasch** [comment]
`^1.4.0` includes `1.8`, see https://github.com/npm/node-semver#caret-ranges-123-025-004.

**Comment by pghalliday** [comment]
After rechecking the docs I see I incorrectly specified the transform. Will try again. Sorry :o

**Comment by janraasch** [comment]
np
