### ISSUE TITLE
Options don't work

### ISSUE THREAD

**Issue by justnorris** [janraasch/gulp-coffeelint#30]
Created "coffeelint.json" in project root
~~~
{
  "no_tabs": "ignore"
}
~~~

Still getting errors.
~~~
  ✖  line 32  Line contains tab indentation
~~~

**Comment by janraasch** [comment]
This is not related to `gulp-coffeelint` but simply the `coffeelint.json` formatting given by `coffeelint` (see http://www.coffeelint.org/#usage).

You need to put

```json
{
  "no_tabs": {
    "level": "ignore"
  }
}
```

in your config file.
