### ISSUE TITLE
Make active links from file paths, just like gulp-jshint

### ISSUE THREAD

**Issue by piotrd** [janraasch/gulp-coffeelint#31]
Consider the screenshot:

![image](https://cloud.githubusercontent.com/assets/176665/8452594/76924b72-1fec-11e5-9ef6-e16fc3de7ffa.png)

1) is an output generated by gulp-coffeelint (using coffeelint-stylish reporter)
2) is an output generated by gulp-jshint (using jshint-stylish reporter)

I didn't have a chance to investigate deeper yet, but, to not forget, I'm filing the issue. Any easy explanation why there are no active links to files for gulp-coffeelint? Has it been implemented at all?

**Comment by janraasch** [comment]
Hi @piotrd. Thank you for your interest. Could you explain what you mean by an *active* link please?

**Comment by piotrd** [comment]
Sorry for my brevity. I meant a clickable link.

Now I'm thinking this may have something to do with Webstorm (which I'm using for the project), but not sure yet. I ran gulp in Webstorm and in its console I see the output part of which I showed on the screenshot. As you see, the path marked with (2) has a different style and, when clicked, takes me to the exact file, line and column the error is reported in. It doesn't work like that for the path marked as (1), the one generated by gulp-coffeelint and coffeelint-stylish reporter. Any ideas? I'll try to do a few tests to narrow down the "issue", however I won't be able to do it today.

**Comment by janraasch** [comment]
Thank you for your explaination. I do not use Webstorm, but simply a
normal command-line. Maybe Webstorm only outputs clickable links for
absolute paths? There may also be a way to tell Webstorm to link to
relative paths for your project as they are output by the stylish
coffeelint reporter. Have you tried using another reporter. There maybe
one that prints absolute paths.

I would try:

- Answer the question: Is the problem that the filepaths are relative
  and not absolute?
- Find a way to tell WebStorm that some file paths may be relative to
  your project. (WebStorm based)
- Find another reporter (see README for the built-in ones) or write one
  yourself which outputs absolute paths.


On Wed, Jul 1, 2015, at 08:30 PM, Piotr D wrote:
> Sorry for my brevity. I meant a clickable link.


> Now I'm thinking this may have something to do with Webstorm (which
> I'm using for the project), but not sure yet. I ran gulp in Webstorm
> and in its console I see the output part of which I showed on the
> screenshot. As you see, the path marked with (2) has a different style
> and, when clicked, takes me to the exact file, line and column the
> error is reported in. It doesn't work like that for the path marked as
> (1), the one generated by gulp-coffeelint and coffeelint-stylish
> reporter. Any ideas? I'll try to do a few tests to narrow down the
> "issue", however I won't be able to do it today.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/janraasch/gulp-coffeelint/issues/31#issuecomment-117788749

**Comment by janraasch** [comment]
No action in two month. Thus I am closing this.
