### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by piotrd** [janraasch/gulp-coffeelint#41]
Hi,

Since version 0.5.0 there have been quite a few commits made (mainly dependency updated). Can we expect a version bump (and an update in npm/bower registries) with those changes anytime soon?

**Comment by janraasch** [comment]
Hi @piotrd, you are right. The only change that is actually relevant is the switch to `through2 v2` (see https://github.com/janraasch/gulp-coffeelint/compare/v0.5.0...master), but then again that is also hidden from userland by the gulp API.

I'll cut a minor release though, just to be sure we are not breaking people's downstream code.

**Comment by janraasch** [comment]
`v0.6.0` is now live on [npm](https://www.npmjs.com/package/gulp-coffeelint).

**Comment by piotrd** [comment]
Thanks for prompt action!
