### ISSUE TITLE
coffelint options

### ISSUE THREAD

**Issue by houd1ni** [janraasch/gulp-coffeelint#45]
Hi! I've created .json with options, directed the plugin to read it (with a wrong path it throws an error), but nothing changed in test reports!

``` clint.json:
{
  "no_interpolation_in_single_quotes": "warn",
  "no_unnecessary_double_quotes": "warn",
  "braces_spacing": "warn",
  "no_interpolation_in_single_quotes": "error"
}
```
Though, mistypes like ``` fn<"ho!") ``` it catches (paths to *.coffee are OK).

How to fix it? Is it coffeelint feature, or should I change clint.json ?
Huge thanks!

**Comment by janraasch** [comment]
Hi @houd1ni, it seems like your config is *wrongly* formatted. See http://www.coffeelint.org/#options.

In order to set the *level* of an option, you need to specify its `level` key, so your config should look like this:

```json
{
  "no_interpolation_in_single_quotes":  {
    "level": "warn"
  },
  "no_unnecessary_double_quotes": {
    "level": "warn"
  },
  "braces_spacing": {
    "level": "warn"
  },
  "no_interpolation_in_single_quotes": {
    "level": "error"
  }
}
```

Hope that helps.

**Comment by houd1ni** [comment]
Yes, it done. Official options docs doesn't provide any useful docs to this. Thank you!!
