### ISSUE TITLE
Bug in readme.me Usage example

### ISSUE THREAD

**Issue by marverix** [janraasch/gulp-coffeelint#56]
Hi,

there is small bug in readme.md Usage section. You forgot to add "return". Without it it's not working correctly and other tasks are not waiting for coffeelint task to finish.

I have created PR already: https://github.com/janraasch/gulp-coffeelint/pull/55

Cheers!

**Comment by janraasch** [comment]
Thank you. I moved the description over to the pr. No need to track this twice.
