### ISSUE TITLE
When 'fail' reporter is used, it does not always return all failures

### ISSUE THREAD

**Issue by peternied** [janraasch/gulp-coffeelint#60]
I am seeing inconsistent behavior where not all lint errors would be reported to the console before the gulp task errors out.

This makes it hard to get developers to fix errors shown in CI pipelines

**Comment by janraasch** [comment]
Hi Peter

> This makes it hard to get developers to fix errors shown in CI pipelines

I'd be interested to talk about the things that make it hard to get developers to fix errors in general ;)

Okay, jokes aside, could you please provide more details. A reproducable example or failing test case would be great.

**Comment by peternied** [comment]
I think it is related to how the file isn't pushed if there are failures in the failReporter; however, I'll figure out whats going on in my codebase and re-open with proper repro steps when I've got them
